# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340530dd2d54fb27f39cf4b5e91d439f24dd3344404d7832d59673369ab7b81f6fdc89870cf1c5b3ad594de66eb357d826e1bfc97a72c16d5ab3fa33245471f0

test:
  secret_key_base: dc0294475fd258ac7d84237285cf42bc6d58f021b0213f4e26d97c38cd6f3389acae40a9b80be9be0ca1ff50d0b1cf718014d9a206e45be73dd690aa0806cf27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
